### ISSUE TITLE
Launch puppeteer in Flutter android

### ISSUE THREAD

**Issue by DevAndr** [xvrh/puppeteer-dart#102]
Hi, trying to do this:
`print("start");
    var browser = await puppeteer.launch();

    var myPage = await browser.newPage();
    await myPage.goto('https://www.github.com', wait: Until.networkIdle);
    await print(myPage.url);
    print("end");
//    var title = await myPage.evaluate('() => document.title');
    await browser.close();`

and throws a mistake:
flutter read-only file system, errno 30

**Comment by YusukeIwaki** [comment]
Flutter doesn't allow us to 

* create temporary directory for user profile
* fork process to launch Google Chrome

I think puppeteer-dart is intended to use as a command-line tool in Win/Mac/Linux.

**Comment by xvrh** [comment]
We can’t use puppeteer on a mobile OS (android or iOS) because we can’t launch a process on those platforms. Even if we could, I’m not sure Chrome support the « automation » mode on mobile.

But you can use puppeteer-dart on Flutter either with:
- Flutter on Desktop (macOS, windows, Linux)
- Or on mobile but with the actual Chrome instance running on a server and accessed by the mobile app with `puppeteer.connect`

Hope that helps :-)

**Comment by DevAndr** [comment]
thanks)
Will have through the server
